AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Stack that creates an Athena table for querying partitioned
    CloudFront access logs.

Parameters:
  ResourcePrefix: 
    Type: String
    ConstraintDescription: '[a-z0-9]+/'
    MinLength: 1
    MaxLength: 20
    Description: >
        Prefix that is used for the created resources (20 chars, a-z and 0-9 only)
  GzKeyPrefix: 
    Type: String
    Default: 'partitioned-gz/'
    ConstraintDescription: '[A-Za-z0-9\-]+/'
    Description: >
        Prefix of gzip'ed access log files
  BucketName:
    Type: String
    ConstraintDescription: '[A-Za-z0-9\-]+/'
    Description: >
      Bucket where the gzip'ed log files are stored
Resources:
# Glue Resources
# - Database
# - Partitioned Gzip Table

    CfLogsDatabase:
        Type: AWS::Glue::Database
        Properties:
          CatalogId: !Ref AWS::AccountId
          DatabaseInput:
            Name: !Sub "${ResourcePrefix}_cf_access_logs_db"
    PartitionedGzTable:
      Type: AWS::Glue::Table
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: !Ref CfLogsDatabase
        TableInput:
          Name: 'partitioned_gz'
          Description: 'Gzip logs delivered by Amazon CloudFront partitioned'
          TableType: EXTERNAL_TABLE
          Parameters: { "skip.header.line.count": "2" }
          PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string
          - Name: day
            Type: string
          - Name: hour
            Type: string
          StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            Columns:
            - Name: date
              Type: date
            - Name: time
              Type: string
            - Name: location
              Type: string
            - Name: bytes
              Type: bigint
            - Name: request_ip
              Type: string
            - Name: method
              Type: string
            - Name: host
              Type: string
            - Name: uri
              Type: string
            - Name: status
              Type: int
            - Name: referrer
              Type: string
            - Name: user_agent
              Type: string
            - Name: query_string
              Type: string
            - Name: cookie
              Type: string
            - Name: result_type
              Type: string
            - Name: request_id
              Type: string
            - Name: host_header
              Type: string
            - Name: request_protocol
              Type: string
            - Name: request_bytes
              Type: bigint
            - Name: time_taken
              Type: float
            - Name: xforwarded_for
              Type: string
            - Name: ssl_protocol
              Type: string
            - Name: ssl_cipher
              Type: string
            - Name: response_result_type
              Type: string
            - Name: http_version
              Type: string
            - Name: fle_status
              Type: string
            - Name: fle_encrypted_fields
              Type: int
            - Name: c_port
              Type: int
            - Name: time_to_first_byte
              Type: float
            - Name: x_edge_detailed_result_type
              Type: string
            - Name: sc_content_type
              Type: string
            - Name: sc_content_len
              Type: bigint
            - Name: sc_range_start
              Type: bigint
            - Name: sc_range_end
              Type: bigint
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Sub "s3://${BucketName}/${GzKeyPrefix}"
            SerdeInfo:
              Parameters:
                field.delim": "\t"
                serialization.format: "\t"
              SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe